---

- name: Git | user config is created
  become: yes
  become_user: "{{ user_info.login }}"
  template:
    src: gitconfig
    dest: "/home/{{ user_info.login }}/.gitconfig"
  vars:
    git_user_name: "{{ user_info.full_name }}"
    git_user_email: "{{ user_info.email }}"

- name: Git | user-global git ignore file is created
  become: yes
  become_user: "{{ user_info.login }}"
  template:
    src: gitignore_global
    dest: "/home/{{ user_info.login }}/.gitignore_global"
