---

- name: Service Account | GCP service account is copied
  become: yes
  become_user: "{{ user_info.login }}"
  copy:
    src: conf/trainees-keys/{{ user_info.login }}-gcp-service-account.key.json
    dest: /home/{{ user_info.login }}/gstack-bosh-environment/conf/gcp-service-account.key.json
    owner: "{{ user_info.login }}"
    mode: 0600
